GET http://localhost:8080/api/restaurants/999

###

POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "name": "Bratwursthäusle",
  "address": "Nürnberg",
  "cuisine": "Fränkisch"
}

###

POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "name": "",
  "address": "",
  "cuisine": ""
}