GET http://localhost:8080/api/restaurants/1

###

GET http://localhost:8080/api/restaurants

###

POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "name": "Bratwursthäusle",
  "address": "Nürnberg",
  "cuisine": "Fränkisch"
}

###

POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "name": "",
  "address": "",
  "cuisine": ""
}

###

PUT http://localhost:8080/api/restaurants/1
Content-Type: application/json

{
  "name": "Bratwursthäusle",
  "address": "Nürnberg",
  "cuisine": "Fränkisch"
}

###

DELETE http://localhost:8080/api/restaurants/1