spring.datasource.url=jdbc:postgresql://localhost:5432/quickbite
spring.datasource.username=quickbite
spring.datasource.password=quickbiteADMIN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true